[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "always"
restartPolicyMaxRetries = 5

[deploy.env]
ENVIRONMENT = "production"

