[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "./railway_startup.sh"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "always"
restartPolicyMaxRetries = 5

[deploy.env]
ENVIRONMENT = "production"
LOG_LEVEL = "debug"
DISABLE_DATABASE_CHECK_ON_STARTUP = "true"

